const dataColumns = [
  {
    title: 'First Name',
    isSort: true,
    isSortByString: true,
    id: 'firstName',
    name: 'firstName',
    isVisible: true,
  },
  {
    title: 'Last Name',
    isSort: true,
    isSortByString: true,
    id: 'lastName',
    name: 'lastName',
    isVisible: true,
  },
  {
    title: 'Status',
    isSort: false,
    isSortByString: false,
    id: 'status',
    name: 'status',
    isVisible: true,
  },
  {
    title: 'Age',
    isSort: true,
    isSortByString: false,
    id: 'age',
    name: 'age',
    isVisible: true,
  },
  {
    title: 'Profession',
    isSort: false,
    isSortByString: false,
    id: 'profession',
    name: 'profession',
    isVisible: true,
  },
  {
    title: 'Date',
    isSort: true,
    isSortByString: false,
    id: 'date',
    name: 'date',
    isVisible: true,
  },
  {
    title: 'Salary',
    isSort: true,
    isSortByString: false,
    id: 'salary',
    name: 'salary',
    isVisible: true,
  },
];

export default dataColumns;
